name: ATAC_Analysis
channels:
  - bioconda
  - conda-forge
dependencies:
  - perl >=5.26.2
  - snakemake-minimal >=5.24.1
  - macs2 >=2.2.7.1
  - fastqc
  - trimmomatic
  - hisat2
  - samtools
  - picard =3.1.1
  - ucsc-bedgraphtobigwig
  - sra-tools
variables:
  PYTHONPATH: 
